#!/usr/bin/env python

import sys
import os

import datetime
import pytz
import subprocess

import blitzortung

region = 1

station_ids = []

target_folder_name = "/var/cache/blitzortung/raw/archive/%Y/%m/%d"
target_folder_name = "raw/archive/%Y/%m/%d"

now = datetime.datetime.utcnow()
reference_time = (now - datetime.timedelta(hours=1)).replace(minute=0, second=0, microsecond=0)
reference_time = reference_time.replace(tzinfo=pytz.UTC)

print reference_time

target_folder_for_day_name = reference_time.strftime(target_folder_name)
if not os.path.exists(target_folder_for_day_name):
    os.makedirs(target_folder_for_day_name)

station_source = blitzortung.dataimport.stations()
stations = station_source.get_stations(region=region)
if stations:
    for station in stations:
        station_ids.append(station.get_number())

with h5py.File('data.hdf5') as data_file:

    for index, station_id in enumerate(station_ids):
        raw_data_source = blitzortung.dataimport.raw()
        raw_data = raw_data_source.get_raw_data_since(reference_time, region=region, station_id=station_id)
        print station_id, len(raw_data)

        for raw_event in raw_data:
            print raw_event

