#!/usr/bin/env python

import blitzortung


def get_stations():
    station_db = blitzortung.db.station()

    return station_db.select()


def print_stations(stations):
    for station in stations:
        print station


if __name__ == "__main__":
    stations = get_stations()
    print_stations(stations)
