#!/usr/bin/env python

import blitzortung

def get_stations():
  station_db = blitzortung.db.Station()

  return station_db.select()

def print_stations(stations):
  for station in stations:
    print station.get_number(),station.get_short_name(), station.get_location_name(), station.get_country(), station.get_timestamp()

if __name__ == "__main__":
  stations = get_stations()
  print_stations(stations)
