#!/usr/bin/env python
# -*- coding: utf8 -*-

from __future__ import print_function, division
import sys
import blitzortung

if sys.version > '3':
    unicode = str


def get_stations():
    station_db = blitzortung.db.station()

    return station_db.select()


def print_stations(stations):
    total_count = 0
    offline_count = 0
    for station in stations:
        total_count += 1
        offline_count += 1 if station.is_offline() else 0
        print(unicode(station))
    print(
        "{} stations total, {} ({:.1f}%) offline".format(total_count, offline_count, 100 * offline_count / total_count))


if __name__ == "__main__":
    stations = get_stations()
    print_stations(stations)
