#!/usr/bin/env python

"""

Inserts the service generated json into a influxdb.

Create database:

$ influx
> CREATE DATABASE servicelog

"""

from __future__ import print_function

import datetime
import glob
import json
import logging
import os
import socket
import sys
from optparse import OptionParser

import GeoIP
from influxdb import InfluxDBClient

from blitzortung_server.influxdb import DataPoint

logger = logging.getLogger(__name__)
logger.addHandler(logging.StreamHandler(sys.stdout))
logger.setLevel(logging.INFO)

client = InfluxDBClient(
    host='localhost',
    port=8086,
    database='servicelog',
    username='servicelog',
    password='servicelog',
    timeout=5)


def is_valid_ip_address(ip_address_string):
    try:
        addr_bytes = socket.inet_aton(ip_address_string)
        if ip_address_string.count('.') == 3:
            return True
    except socket.error:
        pass
    return False


parser = OptionParser()

parser.add_option("--debug", dest="debug", default=False, action="store_true", help="enable debug output")

(options, args) = parser.parse_args()

if options.debug:
    logger.setLevel(logging.DEBUG)

geoip = GeoIP.open('/etc/alternatives/GeoIPCity.dat', GeoIP.GEOIP_STANDARD)

latest_time = None
logger.debug("latest time %s" % latest_time)

log_file_name = '/var/log/blitzortung/webservice.log'

json_file_names = glob.glob('/var/log/blitzortung/*.json')

json_file_names.sort()

for json_file_name in json_file_names:

    log_data = []
    with open(json_file_name, 'r') as json_file:

        data = json.load(json_file)

        global_timestamp = datetime.datetime.fromtimestamp(data['timestamp'] / 1000000)

        if 'get_strikes_grid' in data:
            total_count = len(data['get_strikes_grid'])
            print(global_timestamp.strftime("%Y-%m-%d %H:%M:%S"), total_count)

            for entry in data['get_strikes_grid']:
                remote_address = entry[6]

                country_code = None
                version = None
                longitude = None
                latitude = None
                city = None
                if is_valid_ip_address(remote_address):
                    user_agent = entry[7]
                    version = None
                    if user_agent:
                        user_agent_parts = user_agent.split(' ')[0].rsplit('-', 1)
                        version_prefix = user_agent_parts[0]
                        version_string = user_agent_parts[1] if len(user_agent_parts) > 1 else None
                        if version_prefix == 'bo-android':
                            version = int(version_string)

                    geo_info = geoip.record_by_addr(remote_address)
                    if geo_info is not None:
                        longitude = round(geo_info['longitude'], 4)
                        latitude = round(geo_info['latitude'], 4)
                        city = geo_info['city']
                        city = city.decode('latin1') if city is not None else None
                        country_code = geo_info['country_code'] if geo_info else None

                timestamp = entry[0]
                minute_length = entry[1]
                grid_baselength = entry[2]
                minute_offset = entry[3]
                region = entry[4]
                count_threshold = entry[5]

                tags = {
                    'region': region,
                    'grid_baselength': grid_baselength,
                    'minute_offset': minute_offset,
                    'minute_length': minute_length,
                    'count_threshold': count_threshold,
                    'country_code': country_code,
                    'version': version
                }

                fields = {
                    'longitude': longitude,
                    'latitude': latitude,
                    'city': city if city is not None else '-'
                }

                data_point = DataPoint("servicelog", time=timestamp * 1000, tags=tags, fields=fields)
                log_data.append(data_point.get())

    client.write_points(log_data)
    os.unlink(json_file_name)
